# Databricks notebook source
# MAGIC %sql
# MAGIC
# MAGIC CREATE DATABASE IF NOT EXISTS KPI_CLOUD_BL LOCATION '/kpi_cloud_bl';
# MAGIC
# MAGIC CREATE DATABASE IF NOT EXISTS KPI_CLOUD_SL LOCATION '/kpi_cloud_sl';
# MAGIC
# MAGIC CREATE DATABASE IF NOT EXISTS KPI_CLOUD_GL LOCATION '/kpi_cloud_gl';
# MAGIC
# MAGIC CREATE DATABASE IF NOT EXISTS kpi_etl_analytics_conf LOCATION '/kpi_etl_analytics_conf';
