name: Deploy Databricks
run-name: Deploy Databricks

on:
  workflow_dispatch:
    
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.2.0

      - name: Databricks Deploy
        uses: antstackio/databricks-deploy@v1.0.4
        with:
          databricks-repo-branch: 'master'
          databricks-token: 'dapi3c1c4d97fd3a6a1638271b3900a3e55c'
          databricks-host: 'https://adb-6561072317183116.16.azuredatabricks.net'
          databricks-repo-id: '1019267213786490'
################### End of workflow file ###################
