name: Deploy Databricks
run-name: Deploy Databricks

on:
  workflow_dispatch:
    
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.2.0

      - name: Databricks Deploy
        uses: antstackio/databricks-deploy@v1.0.4
        with:
          databricks-repo-branch: 'master'
          databricks-token: 'dapiad9348dacdf310c8362251511c6b3c2a'
          databricks-host: 'https://adb-3764127576722237.17.azuredatabricks.net'
          databricks-repo-id: '1019267213786489'
################### End of workflow file ###################
