name: Deploy Databricks
run-name: Deploy Databricks

on:
  workflow_dispatch:
    
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.2.0

      - name: Databricks Deploy
        uses: antstackio/databricks-deploy@v1.0.4
        with:
          databricks-repo-branch: 'master'
          databricks-token: 'dapi28d9aeda552e88d1c599aea7914463c0'
          databricks-host: 'https://adb-6561072317183116.16.azuredatabricks.net'
          databricks-repo-id: '3422444267223143'
################### End of workflow file ###################
